{
 "title": "Teltonika Mobile",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(teltonika_cpu_usage,device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teltonika_mobile_connected{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receiving",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(teltonika_mobile_data_received{device=\"$device\"}[$__range]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(teltonika_mobile_data_sent{device=\"$device\"}[$__range]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "teltonika_cpu_usage{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(teltonika_mobile_data_received{device=\"$device\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(teltonika_mobile_data_sent{device=\"$device\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(teltonika_device_uptime{device=\"$device\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mobile uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(teltonika_mobile_uptime{device=\"$device\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "description": "Mobile chip temperature",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(teltonika_mobile_temperature{device=\"$device\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(deriv(teltonika_mobile_data_received[1m])) * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "sum (deriv(teltonika_mobile_data_sent[1m])) * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "avg(teltonika_mobile_signal_strength)",
     "legendFormat": "RSSI"
    },
    { "expr": "-70", "legendFormat": "Limit" }
   ]
  },
  {
   "title": "RSRQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "avg(teltonika_mobile_rsrq)", "legendFormat": "RSRQ" },
    { "expr": "-15", "legendFormat": "Limit" }
   ]
  },
  {
   "title": "RSRP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "avg(teltonika_mobile_rsrp)", "legendFormat": "RSRP" },
    { "expr": "-85", "legendFormat": "Limit" }
   ]
  },
  {
   "title": "SINR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "avg(teltonika_mobile_sinr)", "legendFormat": "SINR" },
    { "expr": "12", "legendFormat": "Limit" }
   ]
  }
 ]
}