{
 "title": "Teltonika WiFi clients",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sclient",
    "label": "Connected wifi client",
    "query": {
     "query": "label_values(teltonika_wireless_client_signal,client)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current signal",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "avg(teltonika_wireless_client_signal{client=~\"${sclient}\"}) by (client,device)",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "WiFi Client count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (device) (count by (client, device) (teltonika_wireless_client_signal))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device signal",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "avg by (client, device, radio) (teltonika_wireless_client_signal{client=~\"${sclient}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low signal devices",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "avg by (client, device, radio) (teltonika_wireless_client_signal{client=~\"${sclient}\"}) < -75",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wifi utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (device, radio) (teltonika_wireless_device_airtime_utilization)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "avg by (device, radio) (teltonika_wireless_device_signal)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device noise",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "avg by (device, radio) (teltonika_wireless_device_noise)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}